/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HangarRouteImport } from './routes/hangar'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TestShipOwnershipRouteImport } from './routes/test-ship-ownership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HangarRoute = HangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TestShipOwnershipRoute = TestShipOwnershipRouteImport.update({
  id: '/test-ship-ownership',
  path: '/test-ship-ownership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/test-ship-ownership': typeof TestShipOwnershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/test-ship-ownership': typeof TestShipOwnershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/test-ship-ownership': typeof TestShipOwnershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hangar' | '/market' | '/profile' | '/test-ship-ownership'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hangar' | '/market' | '/profile' | '/test-ship-ownership'
  id:
    | '__root__'
    | '/'
    | '/hangar'
    | '/market'
    | '/profile'
    | '/test-ship-ownership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HangarRoute: typeof HangarRoute
  MarketRoute: typeof MarketRoute
  ProfileRoute: typeof ProfileRoute
  TestShipOwnershipRoute: typeof TestShipOwnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangar': {
      id: '/hangar'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof HangarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-ship-ownership': {
      id: '/test-ship-ownership'
      path: '/test-ship-ownership'
      fullPath: '/test-ship-ownership'
      preLoaderRoute: typeof TestShipOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HangarRoute: HangarRoute,
  MarketRoute: MarketRoute,
  ProfileRoute: ProfileRoute,
  TestShipOwnershipRoute: TestShipOwnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
